// This file is auto-generated by the Supabase CLI
// See: https://supabase.com/docs/guides/api/generating-types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          role: 'ADMIN' | 'USER';
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          role?: 'ADMIN' | 'USER';
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          role?: 'ADMIN' | 'USER';
        };
      };
      ActivityLog: {
        Row: {
          id: string
          userId: string
          analysisType: 'text' | 'image'
          inputData: string
          resultLabel: string
          resultConfidence: number
          resultAllScores: string
          resultReferences: string | null
          extractedText: string | null
          createdAt: string
          updatedAt: string
        }
        Insert: {
          id?: string
          userId: string
          analysisType: 'text' | 'image'
          inputData: string
          resultLabel: string
          resultConfidence: number
          resultAllScores: string
          resultReferences?: string | null
          extractedText?: string | null
          createdAt?: string
          updatedAt?: string
        }
        Update: {
          id?: string
          userId?: string
          analysisType?: 'text' | 'image'
          inputData?: string
          resultLabel?: string
          resultConfidence?: number
          resultAllScores?: string
          resultReferences?: string | null
          extractedText?: string | null
          createdAt?: string
          updatedAt?: string
        }
      }
    }
    Views: {
      // Define your database views here
    }
    Functions: {
      // Define your database functions here
    }
    Enums: {
      // Define your enums here
    }
  }
}
